### ISSUE TITLE
not updating the document (500 Internal Server Error)

### ISSUE THREAD

**Issue by CyberSardinha** [B-urb/doclytics#96]
I have installed the latest version of doclytics, created the custom fields in paperless, installed and tested ollama, but I'm still getting this error and can't do any documents.

Any idea of what is the problem?

> Error: reqwest::Error { kind: Status(500), url: "http://192.168.0.2:6791/api/documents/520/" }
> Sep 15 08:07:39.418 INFO Application started, version: 1.1.4-rc.9
> Sep 15 08:07:39.467 INFO Fetching custom fields from paperless at http://192.168.0.2:6791
> Sep 15 08:07:39.467 DEBG starting new connection: http://192.168.0.2:6791/
> Sep 15 08:07:39.478 INFO Fields: [Field { id: 11, name: "category", data_type: "string" }, Field { id: 10, name: "date_received", data_type: "string" }, Field { id: 9, name: "topic", data_type: "string" }, Field { id: 8, name: "recipient", data_type: "string" }, Field { id: 7, name: "urgency", data_type: "string" }, Field { id: 6, name: "sender", data_type: "string" }, Field { id: 5, name: "tagged", data_type: "string" }]
> Sep 15 08:07:39.478 INFO Retrieve Documents from paperless at: http://192.168.0.2:6791, with query: NOT tagged=true
> Sep 15 08:07:39.780 INFO Successfully retrieved 25 Documents
> Sep 15 08:07:39.780 INFO Generate Response with LLM model
> Sep 15 08:07:39.780 DEBG starting new connection: http://192.168.0.2:11434/
> Sep 15 08:08:20.997 INFO Updating document with ID: 520
> Sep 15 08:08:20.997 DEBG starting new connection: http://192.168.0.2:6791/
> Sep 15 08:08:21.043 ERRO Error while updating document fields: HTTP status server error (500 Internal Server Error) for url (http://192.168.0.2:6791/api/documents/520/)

**Comment by CyberSardinha** [comment]
I managed to get the logs from paperless i still cant figure out what the problem is

> 
> [2024-09-24 12:01:44,796] [ERROR] [django.request] Internal Server Error: /api/documents/519/
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
>     raise exc_info[1]
>   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
>     response = await get_response(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
>     raise exc_info[1]
>   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
>     response = await wrapped_callback(
>                ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 468, in __call__
>     ret = await asyncio.shield(exec_coro)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 522, in thread_handler
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
>     return view_func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 124, in view
>     return self.dispatch(request, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
>     response = self.handle_exception(exc)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
>     self.raise_uncaught_exception(exc)
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
>     raise exc
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
>     response = handler(request, *args, **kwargs)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 82, in partial_update
>     return self.update(request, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/paperless/src/documents/views.py", line 389, in update
>     response = super().update(request, *args, **kwargs)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 67, in update
>     serializer.is_valid(raise_exception=True)
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 223, in is_valid
>     self._validated_data = self.run_validation(self.initial_data)
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 442, in run_validation
>     value = self.to_internal_value(data)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 499, in to_internal_value
>     validated_value = field.run_validation(primitive_value)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 634, in run_validation
>     value = self.to_internal_value(data)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 693, in to_internal_value
>     validated = self.run_child_validation(item)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 653, in run_child_validation
>     return self.child.run_validation(data)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 445, in run_validation
>     value = self.validate(value)
>             ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/paperless/src/documents/serialisers.py", line 646, in validate
>     MaxLengthValidator(limit_value=128)(data["value"])
>   File "/usr/local/lib/python3.11/site-packages/django/core/validators.py", line 366, in __call__
>     cleaned = self.clean(value)
>               ^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/django/core/validators.py", line 450, in clean
>     return len(x)
>            ^^^^^^
> TypeError: object of type 'bool' has no len()
> [20
